version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
      - user-service
      - product-service
      - order-service
      - payment-service

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - '4001:4001'
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - '4002:4002'
    depends_on:
      - postgres

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - '4003:4003'
    depends_on:
      - postgres

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - '4004:4004'
    depends_on:
      - postgres

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - '4005:4005'
    depends_on:
      - postgres

volumes:
  pgdata: